# Generated by Django 4.1 on 2022-08-18 16:50

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('author', models.CharField(max_length=1000)),
                ('enrolls', models.IntegerField(default=0)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('link', models.URLField(max_length=2000)),
                ('overall_rating', models.IntegerField(default=0)),
                ('catagory', models.CharField(default='Computer Science', max_length=250)),
                ('platform', models.CharField(default='YouTube', max_length=1000)),
                ('university', models.CharField(blank=True, max_length=1000)),
                ('released_date', models.DateField(auto_now_add=True)),
                ('country', models.CharField(default='India', max_length=1000)),
                ('language', models.CharField(default='English', max_length=250)),
                ('price', models.IntegerField(default=0)),
                ('duration', models.IntegerField(default=4)),
                ('certificate', models.BooleanField(default=False)),
                ('material_type', models.CharField(choices=[('Videos', 'Videos'), ('Textual', 'Textual'), ('Hybrid', 'Hybrid')], default='Videos', max_length=25)),
                ('added_by', models.CharField(default='Neesham', max_length=1000)),
                ('num_of_reviews', models.IntegerField(default=0)),
                ('num_of_ratings', models.IntegerField(default=0)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name_plural': 'Courses',
                'ordering': ['-overall_rating'],
            },
        ),
    ]
