# Generated by Django 4.1 on 2022-08-18 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_enrolls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='overall_rating',
            field=models.FloatField(default=0),
        ),
    ]
