# Generated by Django 4.1 on 2022-08-23 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_overall_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image_mobile',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
